apiVersion: v1
kind: Service
metadata:
  name: go-server-service
  namespace: go-server
  labels:
    app: go-server
spec:
  type: LoadBalancer
  selector:
    app: go-server
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
